micronaut:
  application:
    name: demo
  security:
    authentication: bearer
    token:
      roles-name: 'authorities'
      jwt:
        enabled: true
        signatures:
          jwks:
            keycloak:
              url: "http://localhost:8088/auth/realms/myrealm/protocol/openid-connect/certs"
  server:
    netty:
      compression-threshold: 0